name: Build danser

on:
  push:

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install winlibs
        uses: bwoodsend/setup-winlibs-action@v1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'
          cache: true

      - name: Build danser
        run: |
          version="snapshot"
          export DANSER_BUILD_MODE=0
          ./dist-win.sh $version
          
          if [ ! -f "dist/artifacts/danser-${version}-win.zip" ]; then
            echo "Danser failed to build"
            exit 1
          fi
        id: build

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !failure() && steps.build.conclusion != 'failure' }}
        with:
          name: danser-win
          path: dist/artifacts/*

  build_linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev libgtk-3-dev

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'
          cache: true

      - name: Build danser
        run: |
          version="snapshot"
          chmod +x dist-linux.sh
          ./dist-linux.sh $version

          if [ ! -f "dist/artifacts/danser-${version}-linux.zip" ]; then
            echo "Danser failed to build"
            exit 1
          fi
        id: build

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !failure() && steps.build.conclusion != 'failure' }}
        with:
          name: danser-linux
          path: dist/artifacts/*
